# Generated by Django 4.2.9 on 2024-01-20 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_box', models.CharField(max_length=100, unique=True, verbose_name='Input Box')),
                ('text_area', models.TextField(unique=True, verbose_name='Text Area')),
            ],
        ),
    ]
